[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-storage"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes       = { workspace = true }
nomos-core  = { workspace = true }
overwatch   = { workspace = true }
rocksdb     = { version = "0.22", optional = true }
serde       = { version = "1.0", features = ["derive"] }
thiserror   = "1.0"
tokio       = { version = "1", features = ["macros", "sync"] }
tracing     = "0.1"

[dev-dependencies]
tempfile = "3"
tokio    = { version = "1", features = ["macros", "sync", "time"] }

[features]
default         = []
mock            = []
rocksdb-backend = ["dep:rocksdb"]

[[bin]]
name              = "rocks"
path              = "src/bin/rocks.rs"
required-features = ["rocksdb-backend"]
