[package]
edition = "2021"
license = { workspace = true }
name    = "kzgrs-backend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff        = "0.4"
ark-poly      = "0.4.2"
ark-serialize = "0.4.2"
blake2        = "0.10"
itertools     = "0.12"
kzgrs         = { workspace = true }
nomos-core    = { workspace = true }
rand          = "0.8.5"
rayon         = { version = "1.10.0", optional = true }
serde         = { version = "1.0", features = ["derive"] }

[dev-dependencies]
ark-bls12-381 = "0.4.0"
divan         = "0.1"
rand          = "0.8"

[features]
default   = []
parallel  = ["dep:rayon", "kzgrs/parallel"]
single    = []
testutils = []

[[bench]]
harness = false
name    = "encoder"

[[bench]]
harness = false
name    = "verifier"

[[bench]]
harness = false
name    = "reconstruct"
