[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-time"
version = "0.1.0"

[dependencies]
async-trait        = "0.1"
cfg_eval           = { version = "0.1", optional = true }
cryptarchia-engine = { workspace = true, features = ["serde", "tokio"] }
futures            = "0.3"
log                = "0.4.22"
nomos-utils        = { workspace = true, features = ["time"], optional = true }
overwatch          = { workspace = true }
serde              = { version = "1.0", optional = true, features = ["derive"] }
serde_with         = { workspace = true, optional = true }
sntpc              = { version = "0.5", optional = true, features = ["tokio-socket"] }
thiserror          = { version = "2.0", optional = true }
time               = "0.3"
tokio              = { version = "1", features = ["macros", "sync"] }
tokio-stream       = "0.1"

[features]
ntp       = ["dep:sntpc", "dep:thiserror"]
serde     = ["dep:cfg_eval", "dep:nomos-utils", "dep:serde", "dep:serde_with"]
testutils = []
