[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-sampling"
version = "0.1.0"

[dependencies]
async-trait              = "0.1"
bytes                    = { workspace = true }
common-http-client       = { workspace = true }
futures                  = "0.3"
hex                      = "0.4.3"
kzgrs-backend            = { workspace = true }
libp2p-identity          = { version = "0.2" }
multiaddr                = "0.18"
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-da-verifier        = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
overwatch                = { workspace = true }
rand                     = "0.8.5"
serde                    = { version = "1.0", features = ["derive"] }
subnetworks-assignations = { workspace = true }
tokio                    = { version = "1", features = ["macros", "sync"] }
tokio-stream             = "0.1.15"
tracing                  = "0.1"
url                      = "2.5.4"

[dev-dependencies]
kzgrs = { workspace = true }

[features]
default         = ["libp2p"]
libp2p          = []
rocksdb-backend = ["nomos-storage/rocksdb-backend"]
