[package]
edition = "2021"
license = { workspace = true }
name    = "nomos-da-verifier"
version = "0.1.0"

[dependencies]
async-trait              = "0.1"
futures                  = "0.3"
kzgrs-backend            = { workspace = true }
libp2p                   = { workspace = true, features = ["ed25519"] }
nomos-core               = { workspace = true }
nomos-da-network-core    = { workspace = true }
nomos-da-network-service = { workspace = true }
nomos-storage            = { workspace = true }
nomos-tracing            = { workspace = true }
overwatch                = { workspace = true }
serde                    = { version = "1.0", features = ["derive"] }
subnetworks-assignations = { workspace = true }
tokio                    = { version = "1", features = ["macros", "sync"] }
tokio-stream             = "0.1.15"
tracing                  = { version = "0.1", features = ["attributes"] }

[features]
libp2p          = []
rocksdb-backend = ["nomos-storage/rocksdb-backend"]
